trigger:
  - master

variables:
  WindowsContainerImage: cdpxwin1809.azurecr.io/global/vse2019:latest
  LinuxContainerImage: cdpxa0712bf275644e58a9d28a8053e650ba00.azurecr.io/official/containerplatform/linux/golang:ms-1.17.9
  ONEBRANCH_AME_ACR_LOGIN: cdpxa0712bf275644e58a9d28a8053e650ba00.azurecr.io

resources:
  repositories:
    - repository: ob-templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main
    - repository: cplat
      type: git
      name: ContainerPlatform/ContainerPlatform
      ref: refs/heads/master

extends:
  template: v2/OneBranch.Official.CrossPlat.yml@ob-templates
  parameters:
    globalSdl:
      suppression:
        suppressionFile: $(Build.SourcesDirectory)\.config\.gdnsuppress
        suppressionSet: default
    stages:
      - template: shared-build-stages.yml@self
